version: "3.9"

services:

  # Warstwa Prezentacji (React)
  frontend:
    build: ./frontend
    container_name: cloud-frontend
    ports:
      - "8080:80"
    networks:
      - cloud-network
    depends_on:
      - backend

  # Warstwa Logiki (.NET) – główne API
  backend:
    build: ./backend
    container_name: cloud-backend
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Server=cloud-db;Database=CreditRiskDb;User Id=sa;Password=StrongPassword123!;TrustServerCertificate=True
      - ScoringServiceUrl=http://scoring-service:3001
    networks:
      - cloud-network
    depends_on:
      - cloud-db
      - scoring-service

  # Mikrousługa scoringowa (Node.js)
  scoring-service:
    build: ./scoring-service
    container_name: scoring-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    networks:
      - cloud-network

  # Warstwa Danych (SQL Edge)
  cloud-db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: cloud-db
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - cloud-network
    volumes:
      - sqlserver-data:/var/opt/mssql

networks:
  cloud-network:
    driver: bridge

volumes:
  sqlserver-data:
    name: credit-risk-sqlserver-data
